### ISSUE TITLE
go back to modifying individual lines instead of using a lot of buffer_redraws

### ISSUE THREAD

**Issue by rawdigits** [rawdigits/wee-slack#114]

**Comment by ishigoemon** [comment]
This is causing problems for me after updating recently, I believe. I made a couple of changes to chanmon.pl to have it process notify_message and notify_private tags, but the new redraws (and history?) cause the chanmon window to replay chunks of channels. I can provide more information if it's useful. 

A quick look in debug spew didn't show any tags to identify redrawn messages vs. the original.

I appreciate your work on wee-slack, and no worries if this isn't a priority. Just wanted to drop a note here. If I can find the time to grok the meaning of weechat tags a bit better I may take a stab at solving it that way.

**Comment by rawdigits** [comment]
thanks for the bump @ishigoemon. i have a branch nearly completed that goes back to the old way. the precision of date storage on messages is a bit of a problem, so sometimes the wrong one is modified. i'm working to ensure this doesn't happen before pushing to master.

**Comment by rawdigits** [comment]
I finally had time to work on this and my initial run at it is working well: https://github.com/rawdigits/wee-slack/pull/124 - hopefully it will test okay and be in master soon.

**Comment by crispin-linden** [comment]
That's awesome! I'll be away from my computer for the weekend, but from 5min of running with that code, it's looking great. Will look more closely at backscroll when I get back, but thumbs up so far!

Thanks!

**Comment by ishigoemon** [comment]
That's awesome! I've only run it for a few minutes, and will be away from my computer for the weekend, but it's looking great so far. I'll look closely at scrollback when I return.

Thanks, and thanks again for wee-slack!

**Comment by rawdigits** [comment]
Handled in the refactor here: https://github.com/rawdigits/wee-slack/pull/124

Note: we still fall back to a full buffer redraw in rare circumstances, but it should be very unlikely unless you are in an extremely large and active channel.
