### ISSUE TITLE
Linkify usernames with a dot

### ISSUE THREAD

**Issue by simonsmith** [rawdigits/wee-slack#119]
Autocompleting of usernames works as expected but if I try a username with a dot it does not hyperlink correctly in Slack UI:

![](https://s3.amazonaws.com/f.cl.ly/items/2f0s1N3W0q1V1O012d3U/Image%202015-10-21%20at%204.50.23%20p.m..png)

As per the chat in IRC I tried [this patch](https://gist.github.com/tfheen/9068930bdc3e4047dba4) but instead it prints out this in the UI:

![screen shot 2015-10-21 at 20 55 42](https://cloud.githubusercontent.com/assets/360703/10648415/204f834a-7836-11e5-8597-9abc1cc91594.png)

Thanks

**Comment by tfheen** [comment]
@simonsmith, can you test the PR in https://github.com/rawdigits/wee-slack/pull/149 and report if this fixes it for you?
