### ISSUE TITLE
Fails to reconnect after waking from sleep

### ISSUE THREAD

**Issue by simonsmith** [rawdigits/wee-slack#120]
Whenever I wake my Mac and check my slack `teamname.slack.com` buffer it just repeatedly tries to reconnect with:

```
23:00:24 SYSTEM | Disconnected from slack, trying to reconnect..
```

If I quit weechat or python reload the plugin then it connects fine.

**Comment by keith** [comment]
I see this problem as well.

**Comment by rawdigits** [comment]
The reconnect code was slightly broken (there was a race condition) before #124. Would you mind testing to see if the latest version fixes this issue?

**Comment by keith** [comment]
I'll comment here if I see this again.

**Comment by rawdigits** [comment]
Going to close this for now, as I've had many successful reconnects since #124 - happy to reopen if someone sees this again.

**Comment by terlar** [comment]
I still experience this most of the time if my computer goes to sleep.
