### ISSUE TITLE
Multiple servers grouping issue

### ISSUE THREAD

**Issue by keith** [rawdigits/wee-slack#125]
Just updated to the latest master and it looks like this commit: https://github.com/rawdigits/wee-slack/commit/3c7a1afc84b6c1131760b042dd7b4eb04c38446e broke how servers and channels are grouped. Example:

<img width="93" alt="screen shot 2015-11-17 at 9 49 10" src="https://cloud.githubusercontent.com/assets/283886/11219709/ca46964c-8d10-11e5-9ca9-2d5c256d626e.png">

As you can see there's no channel name above the first 4 channels, and the channel name that should be there is now above the next group of channels. Checking out the commit right before the one referenced above works fine.

**Comment by rawdigits** [comment]
gah! fixing now.

**Comment by rawdigits** [comment]
pushed a potential fix to master.

**Comment by keith** [comment]
Super fast! And it's fixed! Thanks!
