### ISSUE TITLE
If there is text after a link, the text will be duplicated (display bug)

### ISSUE THREAD

**Issue by JohnMaguire** [rawdigits/wee-slack#131]
For example, this is a link that Slack is unable to hit and generate a title for:

https://bugs.ourdomain.com/browse/BNBS-21395

I sent: "https://bugs.ourdomain.com/browse/BNBS-21395 <-- btw, we really need to deal with this soon-ish"

wee-slack rendered: "https://bugs.ourdomain.com/browse/BNBS-21395 <-- btw, we really need to deal with this soon-ish<-- btw, we really need to deal with this soon-ish"

**Comment by rawdigits** [comment]
Ah yes - i have this bug too. It is related to the new redraw methods, which are more efficient but need to be tweaked here.

**Comment by rawdigits** [comment]
this appears to have been fixed. please let me know if you still see it @JohnMaguire
