### ISSUE TITLE
wee-slack read state not sync'd with Slack

### ISSUE THREAD

**Issue by keith** [rawdigits/wee-slack#132]
It seems like somewhere between c9e801e and 9e0db5b827768d2b406787b609f400343b8929f6 (current master) wee-slack marking messages as read was broken. Currently if I receive a message, read/respond to it via wee-slack and then open Slack.app, the message is still unread. This also means if you relaunch weechat the buffers are again marked as unread. I also ran `/slack setallreadmarkers` and it did not solve the problem.

**Comment by keith** [comment]
Turns out this might not be a wee-slack problem. Even the first commit I mentioned stopped correctly writing the read state, now I wonder if it's slack/slack.app

**Comment by tfheen** [comment]
Does this apply to normal messages?  I'm not seeing this (but I'm seeing something slightly related where we highlight some messages on startup even though they're not generating highlights in a running wee-slack, due to the smart irc filter).

**Comment by keith** [comment]
Yep, I'm seeing this on DMs, channel notifications, and just channel unread state.

**Comment by keith** [comment]
Seems like this has resolved itself. So I guess this is on the API side.
