### ISSUE TITLE
New DMs open without messages

### ISSUE THREAD

**Issue by keith** [rawdigits/wee-slack#134]
I've noticed a few times recently that DMs have been opened by the other party sending me a message, but there is no highlight, and when I go to the newly opened buffer there is no message. But then when I check in Slack.app I have missed a message. I'm not seeing this 100%, but it might be something to look out for.

**Comment by rawdigits** [comment]
I couldn't get it to happen in testing yesterday. I'm going over the 'hashtable' finders again with a fine comb.

**Comment by tfheen** [comment]
@keith Are you still seeing this? I don't think I've ever seen it.  Any idea what might be contributing factors?
