### ISSUE TITLE
Error closing buffer

### ISSUE THREAD

**Issue by pigmonkey** [rawdigits/wee-slack#138]
If I `/close` a buffer representing a direct message, it closes successfully but I get the following error in the main window:

```
weechat   ⚠ │ python: wrong arguments for function "buffer_set" (script: slack_extension)
weechat     │ python: stdout/stderr: TypeError: must be string, not None
weechat   ⚠ │ python: error in function "slack_websocket_cb"
```

**Comment by rawdigits** [comment]
I have some of these too. We'll find what is trying to access the closed buffer.

**Comment by JohnMaguire** [comment]
I got this when hiding my "relay.list" buffer with `/buffer hide`
