### ISSUE TITLE
Feature request - shorten urls

### ISSUE THREAD

**Issue by synic** [rawdigits/wee-slack#139]
When I was using the irc gateway, my url shorteners would work.

`wee-slack` is much better, but my url shorteners do not work, meaning I have to type `ALT+L` to get the raw display, and then click on the url (not a huge deal, but just another step).

**Comment by rawdigits** [comment]
good thought. i don't enjoy using alt+l either! which shortener do you use?

**Comment by pigmonkey** [comment]
I use the [urlserver](https://weechat.org/scripts/source/urlserver.py.html/) plugin. One of its features is inserting shortened URLs into the message. This doesn't work in wee-slack buffers, which is kind of annoying. It would be great if wee-slack could support urlserver.

**Comment by synic** [comment]
I use [shortenurl.py](https://weechat.org/scripts/source/shortenurl.py.html/), but not for any specific reason other than I tried it, and it worked.

**Comment by tfheen** [comment]
`shortenurl.py` seems to work fine for me in testing now, so I'll close this bug.

**Comment by pigmonkey** [comment]
Yes, the urlserver plugin started working again after a wee-slack commit in the beginning of November. I forgot that there was an issue to update. Thanks!

**Comment by rstad** [comment]
Do these still work?  I have been trying to get a url shortener to work but it seems like the expected signals to hook aren't showing up and I am uncertain on if it is the specific shortener I was testing with, or if something has changed in the last couple years.
