### ISSUE TITLE
DMs to wrong person.

### ISSUE THREAD

**Issue by rawdigits** [rawdigits/wee-slack#141]
As they say:
"There are only two hard things in Computer Science: cache invalidation and naming things."

This bug is related to the hashtable not being updated properly when a buffer goes away. Because many other things update the entire hashtable, this was infrequent as it required 1) a buffer to be created with a pointer that collides with a previous buffer's pointer and 2) no update_hashtable calls in the meantime.

**Comment by rawdigits** [comment]
This is fixed in #142 by always updating the channels and server.channels hashtables when we attach or detach any buffer.

**Comment by mrrsm** [comment]
:+1: This bit me a couple times sending to the wrong person

**Comment by rawdigits** [comment]
sorry about that! hope this bug didn't get anyone fired. :)
