### ISSUE TITLE
Trello issue comments don't render well: pretext

### ISSUE THREAD

**Issue by FauxFaux** [rawdigits/wee-slack#145]
For the cheapo Trello integration, cards work well, but comments miss a load of context.  This bug affects the IRC gateway too, and they're also not fixing it there.  I guess `pretext` is a new feature.

New card:

    11/12:59:16 Trello :] │ New card "https://trello.com/c/afafa (test)" added to list "https://trello.com/b/afafa (Inbox)"

Comments are a bit broken, though:

    11/12:59:41 Trello :] │ test

In the web client, this renders as:

    New comment on card "<a href="https://trello.com/c/afafa">test</a>" by John Johninson
     | test

The `message_json` comes through as:

```json
{
  "attachments": [
    {
      "color": "8daec2",
      "text": "test",
      "fallback": "test",
      "id": 1,
      "pretext": "New comment on card \"<https://trello.com/c/afafa|test>\" by John Johninson"
    }
  ],
  "text": "",
  "ts": "1449838781.001147",
  "subtype": "bot_message",
  "mrkdwn": true,
  "_server": "afafa.slack.com",
  "type": "message",
  "channel": "afafa",
  "bot_id": "afafa"
}
```

Adding:

```python
if "pretext" in attachment:
    t.append(attachment["pretext"])
```

... to `unwrap_attachments` isn't very effective, as it causes the thing to read backwards; it looks like that message unpacker would need heavy adjustments?

    11/13:19:20 Trello :] │ Here's the comment: New comment on card "https://trello.com/c/awawawa (test)" by John Johninson

**Comment by FauxFaux** [comment]
Aha, I was being dumb.  All the content is in the attachment, so you can actually do it with just `unwrap_attachment`.

**Comment by tfheen** [comment]
I did some changes to formatting here recently, did that make the problem go away?

**Comment by FauxFaux** [comment]
This is great; thanks.
