### ISSUE TITLE
Overlapping text on newly created channels

### ISSUE THREAD

**Issue by tricksunga** [rawdigits/wee-slack#146]
Not sure if this has been reported before.

When someone creates a new channel and you haven't restarted weechat, the new channel shows up as last buffer (even after the last person on the team), and if someone is typing on the new channel, the "someone is typing status" `>` overlaps the first character of the channel name.

i.e.
76. slackbot (last person on the team)
77. new-channel
78. slack-debug

if someone is typing on the channel
76. slackbot (last person on the team)
77. >ew-channel
78. slack-debug

notice the `>ew-channel`

**Comment by rawdigits** [comment]
This can be repro'd by creating a new channel. it sometimes (always) appears as 'channelname' instead of '#channelname', so when typing happens, the first char is overwritten
