### ISSUE TITLE
Buffers.pl foreground color

### ISSUE THREAD

**Issue by Keithbsmiley** [rawdigits/wee-slack#16]
The foreground color in the buffer list has the correct background color but incorrect selected foreground color. This can lead to unreadable names and channels. This also applies to the foreground color for unread channels.

**Comment by pbrisbin** [comment]
I also notice that my slack buffers don't tab complete for the `/buffer` command. Is it possible these buffers aren't "real" in some sense?

**Comment by rawdigits** [comment]
possibly? i think /buffers (name) uses the long name, which would be (yourdomain).slack.com.(channelname)

**Comment by rawdigits** [comment]
(finally) fixed: https://github.com/rawdigits/wee-slack/pull/39 
thanks to @ishigoemon

**Comment by Keithbsmiley** [comment]
Woo!
