### ISSUE TITLE
WeeChat crashes 

### ISSUE THREAD

**Issue by furai** [rawdigits/wee-slack#162]
I'm not exactly sure why it happened so I cannot give more help. Attaching 2 crashes.
I was fiddling with away messages, tried to set on attach and on detach commands in the script for "/slack away" and "/slack back". But that didn't trigger the crash directly. No idea what did. It happened in the middle of using the plugin.

See the attached crash dumps.

**Comment by trygveaa** [comment]
Did you attach the crash dumps? I can't see any attachments.

**Comment by furai** [comment]
They were here but got removed by maintainer.

**Comment by rawdigits** [comment]
We weren't able to get these to happen, but think it is triggered by the interaction with another plugin. It is probably closing the buffer before we know about it and causing a race condition.
