### ISSUE TITLE
[enhancement request] Support private/direct messaging a user WITH the message in tow

### ISSUE THREAD

**Issue by megalithic** [rawdigits/wee-slack#167]
Hipchat, irc, etc support being able to private message a user along with the message itself. Presently, via wee-slack, we're able to `/query [username]`, but we're not able to `/query [username] [message]`.

Some suggestions for not messing with `/query`, would be:
`/msg [username] [message]`, or `/pm [username] [message]`.

Would be super useful/handy/streamline private/direct messaging people.

**Comment by tfheen** [comment]
]] Seth Messer 

> Some suggestions for not messing with /query, would be:
> /msg [username] [message], or /pm [username] [message].

/msg username message is the IRC syntax, so I'd prefer if we just used
that.

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by megalithic** [comment]
@tfheen agreed 100%.

**Comment by megalithic** [comment]
@tfheen HERO! thank you sir!!
