### ISSUE TITLE
Add script to official script list

### ISSUE THREAD

**Issue by terlar** [rawdigits/wee-slack#180]
Is there any reason for this not to be added to the official weechat script list in order to have an easier install and discoverability, or is this waiting for version 1.0 (stable)?

This is the page to submit a script:
https://weechat.org/scripts/add/

**Comment by brettmichael** [comment]
I'd love to see it in the official script list so I can just pull it from inside the client.

**Comment by bricewge** [comment]
It is now in the official script list: https://weechat.org/scripts/source/slack.py.html/
This issue can be closed.
