### ISSUE TITLE
AttributeError: 'User' object has no attribute 'nicklist_pointer'

### ISSUE THREAD

**Issue by adamgibbins** [rawdigits/wee-slack#187]
I continue to get this in my core buffer:
```
Traceback (most recent call last):
  File "/home/aeg/.weechat/python/autoload/wee_slack.py", line 1335, in slack_websocket_cb
    proc[function_name](message_json)
  File "/home/aeg/.weechat/python/autoload/wee_slack.py", line 1393, in process_presence_change
    server.users.find(identifier).set_inactive()
  File "/home/aeg/.weechat/python/autoload/wee_slack.py", line 848, in set_inactive
    w.nicklist_nick_set(self.server.buffer, self.nicklist_pointer, "visible", "0")
AttributeError: 'User' object has no attribute 'nicklist_pointer'
error in function "slack_websocket_cb"
```

**Comment by rawdigits** [comment]
@adamgibbins i don't have a good idea on reproducing this. my best guess is that this could happen when a user is deleted from the slack group?

**Comment by adamgibbins** [comment]
I don't recall seeing it again since I filed this issue and I've no clue to what caused it - reloading the plugin fixed it. User disabled (we don't ever remove AFAIK) is a possibility I guess. Wouldn't object to closing this ticket if you've no clues, its not a big issue.

**Comment by tfheen** [comment]
Closing as unreproducible.  Please reopen if you see this again or can reproduce.
