### ISSUE TITLE
Error in join cb

### ISSUE THREAD

**Issue by torhve** [rawdigits/wee-slack#195]
Got this error, not sure how.
```
  File "/home/weechat/.weechat/python/wee_slack.py", line 977, in join_command_cb
    if command_talk(current_buffer, args.split()[1]):
IndexError: list index out of range
```

**Comment by tfheen** [comment]
]] Tor Hveem 

>   File "/home/weechat/.weechat/python/wee_slack.py", line 977, in join_command_cb
>     if command_talk(current_buffer, args.split()[1]):
> IndexError: list index out of range

Do you have the rest of the backtrace?

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by torhve** [comment]
No more of it gets printed, no.

**Comment by rawdigits** [comment]
typing `/join` with no args will print this error. we could catch it instead of the stack track..
