### ISSUE TITLE
wee-slack doesn't report notifications via notification_center.py

### ISSUE THREAD

**Issue by megalithic** [rawdigits/wee-slack#211]
#### Relevant versions
os x: 10.11.4
weechat: 1.4
notification_center.py: 1.3
wee-slack: 0.99.9

#### Expected behavior
All previously setup highlights in weechat buffers, and private message buffers, will trigger a notification to the notification_center plugin.

#### Actual behavior
Only irc, xmpp, and jabber buffers report private message and general highlight instances to the plugin. wee-slack created/managed buffers do not report.

Perhaps there is a setting somewhere I've missed for setting up the wee-slack plugin (undocumented)?
Anyway, please let me know if there are other details you might need to reproduce.

**Comment by keith** [comment]
This script should be edited to hook these signals:

```
    weechat.hook_signal("weechat_pv", "notify", "")
    weechat.hook_signal("weechat_highlight", "notify", "")
```

Then messages from wee-slack will trigger those notification.s

**Comment by megalithic** [comment]
hey, huge thanks @keith; will try it out and submit a PR.

**Comment by tfheen** [comment]
It sounds like there's nothing for wee-slack to do here, right, so ok to close?

**Comment by megalithic** [comment]
yes sir, and @tfheen i hope to get those remaining items straightened out for that PR. had some health issues arise and have been dealing with that this week. thanks for your patience.

**Comment by dhruvasagar** [comment]
This didn't fix it for me, Instead I changed the following : 
From : 
```python
weechat.hook_print('', 'irc_privmsg', '', 1, 'notify', '')
```
To : 
```python
weechat.hook_print('', '', '', 1, 'notify', '')
```
