### ISSUE TITLE
/leave or /part throws error

### ISSUE THREAD

**Issue by cro** [rawdigits/wee-slack#218]
For some of my Slack channels, particularly multi-user private chats, when I /leave or /part I see this in the weeslack console:

```
python: wrong arguments for function "buffer_set" (script: slack_extension)
python: stdout/stderr: TypeError: must be string, not None
```

Haven't dug into the code yet, but wanted to document here in case others see the same problem.

**Comment by terminalmage** [comment]
Looks to be fixed pending merge of https://github.com/rawdigits/wee-slack/pull/212

Also, :wave: @cro! :smile:

**Comment by tfheen** [comment]
This got fixed, so closing.
