### ISSUE TITLE
Cannot join a channel

### ISSUE THREAD

**Issue by farnoy** [rawdigits/wee-slack#22]
```
20:13:07     | python: stdout/stderr: Traceback (most recent call last):
20:13:07     | python: stdout/stderr:   File
             | "/home/kuba/.weechat/python/autoload/wee_slack.py", line 554, in
             | slack_command_cb
20:13:07     | python: stdout/stderr:     cmds[function_name](current_buffer, args)
20:13:07     | python: stdout/stderr:   File
             | "/home/kuba/.weechat/python/autoload/wee_slack.py", line 591, in command_join
20:13:07     | python: stdout/stderr:
             | servers.find(current_domain_name()).channels.find(args).open()
20:13:07     | python: stdout/stderr: AttributeError: 'NoneType' object has no attribute
             | 'channels'
20:13:07 =!= | python: error in function "slack_command_cb"
```

**Comment by NorthIsUp** [comment]
i get the same issue on weechat 1.1

**Comment by fsegouin** [comment]
Same here :(

**Comment by rawdigits** [comment]
I pushed a new version with many changes today. Let me know if you still see the issue.

**Comment by farnoy** [comment]
Still the same exact issue

**Comment by farnoy** [comment]
Although something did change because it automatically quit all my open channels/DMs in the web interface.

**Comment by rawdigits** [comment]
Ah, I see the problem. just pushed an update. Are you trying to run the command on the main weechat buffer?

`/slack join (channel)` must be executed on a slack buffer, as the plugin supports connecting to multiple teams. I have modified wee-slack to default to the first domain if the user is only connected to one team, and to print a better error if connected to multiple.
