### ISSUE TITLE
Custom slash commands not working

### ISSUE THREAD

**Issue by nikolay** [rawdigits/wee-slack#227]
I use OpsGenie, which in Slack has the `/genie` command, but it doesn't work in WeeSlack. Please, advise!

**Comment by rawdigits** [comment]
I don't use custom slash commands, but we should probably support them. Happy to take PRs or even advice on how they would integrate. It's...complicated because of how slash commands pretain to weechat in general.

**Comment by nikolay** [comment]
@rawdigits Okay, let me look into it. Slack support is pretty useless without them.

**Comment by cwegener** [comment]
:+1: I have no clue how to implement it, but I would love to see custom slash commands working in wee-slack!

**Comment by V13Axel** [comment]
So it looks like, when a slash command is called, it's sent very simply as a `POST` to `/api/chat.command`.

I run the command `/commander sg-lookup param1=info param2=moreinfo` and the payload looks like this in Chrome Dev Tools:

```------WebKitFormBoundary[RID info]
Content-Disposition: form-data; name="command"

/commander
------WebKitFormBoundary[RID info]
Content-Disposition: form-data; name="text"

sg-lookup param1=info param2=moreinfo
------WebKitFormBoundary[RID info]
Content-Disposition: form-data; name="channel"

[channel id]
------WebKitFormBoundary[RID info]
Content-Disposition: form-data; name="token"

[api token]
------WebKitFormBoundary[RID info]--```

In our case at least, the bot's response is sent back directly as a message via the websocket, no differently than if we ran the slash command via the Slack client... Which works already. So if the chat.command post gets implemented, the rest should "Just Werk"
