### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by bchretien** [rawdigits/wee-slack#23]
Apparently, UTF-8 is not supported in wee-slack (e.g. try to send a message like "éôàèù").

**Comment by bchretien** [comment]
My commit seems to fix it (tested with accented letters, Japanese etc.), but you may want to review the changes since it was done quickly.

**Comment by rawdigits** [comment]
I'll test this out soon. Thanks!

**Comment by rawdigits** [comment]
Just tested and there is breakage with unicode in channel names (i think?). It works fine for most groups, but one group goes into a reconnect loop due to a unicode ellipsis in the name. Will work on this when I have time.

**Comment by bchretien** [comment]
I haven't tested unicode in channel names, so this sounds quite plausible.

**Comment by rawdigits** [comment]
cool. if you have time to fix the channel name issue i'd appreciate it! if not i'll get to it eventually. i miss being able to send ¯\_(ツ)_/¯ in messages.

**Comment by bchretien** [comment]
I tried using unicode characters for the creation of channels or private groups, but it does not seem possible:
>  You entered some disallowed characters in the name, which we've fixed. Make sure it looks good to you, and try again! 

Are you sure that the issue is not related to the group's logged messages?

**Comment by fsegouin** [comment]
@bchretien I tested your fork and I can't connect to several channels, I got this error:

```
00:11:36 =!= | python: wrong arguments for function "buffer_set" (script: slack_extension)
00:11:36     | python: stdout/stderr: Traceback (most recent call last):
00:11:36     | python: stdout/stderr:   File "/Users/florentsegouin/.weechat/python/autoload/wee_slack.py", line 1123, in url_processor_cb
00:11:36     | python: stdout/stderr:     servers.find(data[1]).connected_to_slack(my_json)
00:11:36     | python: stdout/stderr:   File "/Users/florentsegouin/.weechat/python/autoload/wee_slack.py", line 213, in connected_to_slack
00:11:36     | python: stdout/stderr:     self.create_slack_mappings(login_data)
00:11:36     | python: stdout/stderr:   File "/Users/florentsegouin/.weechat/python/autoload/wee_slack.py", line 248, in create_slack_mappings
00:11:36     | python: stdout/stderr:     self.channels.append(Channel(self, item["name"], item["id"], item["is_member"], item["last_read"], "#", item["members"], item["topic"]["value"]))
00:11:36     | python: stdout/stderr:   File "/Users/florentsegouin/.weechat/python/autoload/wee_slack.py", line 299, in __init__
00:11:36     | python: stdout/stderr:     self.members = set(members)
00:11:36     | python: stdout/stderr: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 18: ordinal not in range(128)
00:11:36 =!= | python: error in function "url_processor_cb"
```

I would really love to have UTF-8 support (french user here)! Please let me know if I can help you.

**Comment by bchretien** [comment]
@fsegouin it seems that one of the members on the channel has a name with unicode characters. You can try to encode `members` to UTF-8 in the `Channel` class and see whether that works for you.

**Comment by rawdigits** [comment]
it looks like there is an issue with unicode in the topic as well. i'm working on it right now..

**Comment by fsegouin** [comment]
@bchretien Thanks for the tip. I ended up editing this line in the ```Channel``` class as you said:

        self.members = set([member.encode('utf-8') for member in members])

I don't know if it's the best way of doing it (I'm new to python) but it definitely works :)

**Comment by bchretien** [comment]
@fsegouin :+1: looks good, so I guess there's just the topic left.

**Comment by rawdigits** [comment]
I added most of your changes in with the latest update. LMK if you see problems.
