### ISSUE TITLE
Feature Request: Support multiple Slack site connections at once.

### ISSUE THREAD

**Issue by suicidepills** [rawdigits/wee-slack#231]
I'm not sure how common this is but I often have a need to connect to multiple slack sites at one time (for different organizations that I'm a part of).  As far as I know, wee_slack doesn't currently support this...

**Comment by adamgibbins** [comment]
Yes it does, per the readme "Optional: If you would like to connect to multiple groups, use the above command with multiple tokens separated by commas. (NO SPACES)" - you just need to specify multiple tokens.

**Comment by suicidepills** [comment]
Very cool.  My bad for not reading the docs :-X  Thank you for your help!
