### ISSUE TITLE
Animated screenshot has disappeared from the readme / repo frontpage

### ISSUE THREAD

**Issue by Nicd** [rawdigits/wee-slack#251]
The image is not found, it was in the following URL but has broken:

https://camo.githubusercontent.com/14cb88182080bafc71bc1edb74b677282ae58d10/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3536363536302f736c61636b2e676966

**Comment by rawdigits** [comment]
fixed! thanks for the reminder.
