### ISSUE TITLE
Reactions print literal message

### ISSUE THREAD

**Issue by bronzehedwick** [rawdigits/wee-slack#253]
I'm running a weechat instance on a FreeBSD server inside tmux.

When I type a reaction, e.g. `3+:smile:`, the output in Slack is +3:smile: as a new message, instead of reacting to the 3rd most recent message.

**Comment by tfheen** [comment]
Weird, I just tried that exact incanation and it shows up as a reaction for me. Are you sure you're running an up-to-date version?

**Comment by rawdigits** [comment]
I also tested this and it worked for me. Make sure you are typing only this on the line (no spaces on either side)

**Comment by tfheen** [comment]
Maybe we should eat any trailing spaces at least?

**Comment by rawdigits** [comment]
Actually trailing space works with the regex (just tested in REPL)
