### ISSUE TITLE
print output from slack commands to slack buffer

### ISSUE THREAD

**Issue by ReubenM** [rawdigits/wee-slack#267]
in core buffer: 
/slack channels => "This command must be used in a slack buffer"

In slack buffer:
/slack channels => *prints channel list to core buffer

me:
*facepalm

Perhaps I'm missing something. Is there anyway to config slack commands to output to current slack buffer? It makes no sense to have one buffer for input and another for output.

**Comment by tfheen** [comment]
In my testing, it prints to the server buffer for the slack instance, not the core buffer. Are you seeing something different?

**Comment by ReubenM** [comment]
Well, it looks like the core and slack server share the same buffer. (?) When listing buffers, core and the slack server both list as buffer 1, but typing a slack command in that buffer clearly goes to core, because it complains about a slack command in the core buffer.

When I go to a slack channel buffer and try to list slack channels, it's output goes to the core / slack server buffer.

**Comment by tfheen** [comment]
Yes, by default the core and server buffers are merged, as described on https://weechat.org/files/doc/devel/weechat_quickstart.en.html#connect_to_irc_server . Try pressing C-x until it says something like ` [python] 1:foo.slack.com` in the status bar and then you have the `foo.slack.com` server buffer active.

**Comment by ReubenM** [comment]
Thanks!
