### ISSUE TITLE
No longer seeing slack generated messages

### ISSUE THREAD

**Issue by kenyonj** [rawdigits/wee-slack#269]
User messages are coming through fine. But, for instance, if someone uses `/giphy` I used to see a link to the gif, but now all I see is `python | organizationname.#channel` like what is shown in the screenshot here:

![](http://i.imgur.com/TVxJPNW.png)

**Comment by mrrsm** [comment]
I have been seeing a ton of those type of messages.  They are coming from most of the bots it looks like.  As well as code snippets people post.

**Comment by kenyonj** [comment]
closing in favor of https://github.com/rawdigits/wee-slack/issues/274
