### ISSUE TITLE
Can't change short_name of buffer

### ISSUE THREAD

**Issue by jhawthorn** [rawdigits/wee-slack#27]
In any slack buffer:

```
/buffer set short_name #testing123
```

Buffer name changes at first, but is then reset to `#general` when focus is moved to another buffer.

**Comment by rawdigits** [comment]
This happens because I modify the short_name to indicate typing in channels:
`#general` becomes `>general`

I think this should become an optional setting. Will add. Thanks!

**Comment by rawdigits** [comment]
We have decided to retain the current behavior for consistency with the other slack clients. If you change channel names in the official slack clients, the change is reflected here. There may be added confusion with limited benefit to letting users change this locally.
