### ISSUE TITLE
Doesnt work with colorize_lines.pl script

### ISSUE THREAD

**Issue by Bigsy** [rawdigits/wee-slack#31]
Firstly thanks for this project its great and I look forward to seeing it get better.

Not sure if its an issue with the script or your plugin but they don't appear to work together. The script appears fine at home where I don't have wee-slack installed but in work it simply doesnt work.

Thanks.

**Comment by rawdigits** [comment]
Thanks!

I will take a look. it may be related to colorization happening within wee-slack. Some scripts only pay attention to irc buffers, and may be ignoring wee-slack's buffers.

**Comment by jeaye** [comment]
I'm also using colorize_lines and am sad to see these two not playing nicely.

**Comment by rawdigits** [comment]
changed here: https://github.com/rawdigits/wee-slack/pull/46

i didn't make colorize_lines.pl work because it depends on some stuff like passing the tag "irc_privmsg" etc etc. it was easier to just colorize myself

**Comment by rodrigomaia17** [comment]
@rawdigits @Bigsy any idea to make it work?
