### ISSUE TITLE
wee-slack keeps crashing on me

### ISSUE THREAD

**Issue by Yavor-Ivanov** [rawdigits/wee-slack#32]
I tried to set up wee-slack as per the instructions, but kept getting this error. Perhaps I missed something? Here's what I did:

1. Installed Weechat 1.1.1 on Ubuntu 14.04.1
2. Installed websocket-client via pip.
3. Downloaded wee_slack.py to ~/.weechat/python/autoload
4. Added my slack key.
5. Saved, reloaded.
6. Tried to list channels with `/slack channels`.

Here's the output (slack key omitted for obvious reasons):
```
  ___       __         ______________        _____ 
  __ |     / /___________  ____/__  /_______ __  /_
  __ | /| / /_  _ \  _ \  /    __  __ \  __ `/  __/
  __ |/ |/ / /  __/  __/ /___  _  / / / /_/ // /_  
  ____/|__/  \___/\___/\____/  /_/ /_/\__,_/ \__/  
WeeChat 1.1.1 [compiled on Jan 28 2015 18:34:24]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
python scripts loaded: slack_extension
Plugins loaded: alias, aspell, charset, exec, fifo, guile, irc, logger, lua, perl, python, relay, ruby, script, tcl,
        trigger, xfer
Option changed: plugins.var.python.slack_extension.slack_api_token = "OMITTED"
Options saved to sec.conf
Options saved to weechat.conf
Options saved to plugins.conf
Options saved to relay.conf
Options saved to script.conf
Options saved to aspell.conf
Options saved to irc.conf
Options saved to charset.conf
Options saved to alias.conf
Options saved to trigger.conf
Options saved to exec.conf
Options saved to xfer.conf
Options saved to logger.conf
python: unloading script "slack_extension"
python: loading script "/home/ppm/.weechat/python/autoload/wee_slack.py"
python: registered script "slack_extension", version 0.97.15 (Extends weechat for typing notification/search/etc on
        slack.com)
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/ppm/.weechat/python/autoload/wee_slack.py", line 669, in slack_command_cb
python: stdout/stderr:     cmds[function_name](current_buffer, args)
python: stdout/stderr:   File "/home/ppm/.weechat/python/autoload/wee_slack.py", line 727, in command_channels
python: stdout/stderr:     for channel in server.channels:
python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'channels'
python: error in function "slack_command_cb"
```

**Comment by Yavor-Ivanov** [comment]
I set up a server connection to the slack IRC gateway server, restarted weechat, and the plugin works fine now.

**Comment by rawdigits** [comment]
Hi there. It's not actually wee-slack crashing, just failing with that commant. You have to execute /slack channels and /slack users from a buffer related to a slack team, not the weechat core buffer. I'll put code in to warn the user, so leaving this issue open..

**Comment by Yavor-Ivanov** [comment]
Actually, I didn't get the slack buffers until after restarting weechat. I figured that reloading python would be enough and tried to run the slack commands in the core buffer (the only one I had open).

**Comment by rawdigits** [comment]
should be fixed in the latest. there is now messaging to let you know when a command won't work in some buffers.
