### ISSUE TITLE
closing a channel makes nicklist crashing

### ISSUE THREAD

**Issue by gabx** [rawdigits/wee-slack#34]
This issue arises when `/close #myChan`in weechat. 
Error messages in main buffer:
```
python: wrong arguments for function "buffer_set" (script: slack_extemsion)
python: stdout/stderr: TypeError : must be a string, not None
python: error in fucntion "slack_websocket_cb"
```

then this repeated  message:
`python: wrong arguments for function "nicklist_add_nick"`

**Comment by rawdigits** [comment]
should be fixed:

https://github.com/rawdigits/wee-slack/commit/0bdb09e299a082c316457b5216969a2723f021aa
