### ISSUE TITLE
Archived channels are always opened on startup

### ISSUE THREAD

**Issue by xiongchiamiov** [rawdigits/wee-slack#38]
We have a few channels that we used for project-specific discussion, and now that those projects are shipped, we've archived them.  However, they still open every time I start wee-slack, even though I've closed them (with `/close`) previously.

**Comment by rawdigits** [comment]
hmmm - this may be related to the cache. can you try removing the cache and restarting? `rm ~/.weechat/slack.cache`

**Comment by xiongchiamiov** [comment]
Nope, still does it.

**Comment by rawdigits** [comment]
I should probably be more specific:

close weechat
rm ~/.weechat/slack.cache
start weechat

if that still doesn't do it, i'll find a way to replicate.

**Comment by xiongchiamiov** [comment]
Yeah, that was what I did.  I wasn't sure, but then I checked my tmux scrollback. :)

**Comment by rawdigits** [comment]
Were the channels normal channels or private groups?

**Comment by xiongchiamiov** [comment]
They were private groups.

**Comment by rawdigits** [comment]
fixed! (finally) 

https://github.com/rawdigits/wee-slack/commit/a84a29dad82d66c5148c8296cb86ae42e129c43d
