### ISSUE TITLE
`/slack talk` should be `/slack query`

### ISSUE THREAD

**Issue by jeaye** [rawdigits/wee-slack#42]
The nomenclature used in wee-slack doesn't follow IRC, weechat, or anything related. To make the usage more intuitive, we should change `/slack talk` to `/slack query`. (weechat has a `/query` command that does exactly that)

**Comment by mrrsm** [comment]
I'm not sure how possible this is but if you can just tap right into the /query command that would be awesome as well.

**Comment by rawdigits** [comment]
changed here: https://github.com/rawdigits/wee-slack/pull/44
