### ISSUE TITLE
Messages that include links are failing

### ISSUE THREAD

**Issue by chishaku** [rawdigits/wee-slack#47]
Any message that includes a link is not showing up in the buffer.  Additionally, I see the following error:

Error: bad file descriptor (10) used in hook_fd

**Comment by rawdigits** [comment]
Does this include messages you send?

**Comment by chishaku** [comment]
No, messages that I send work as expected.

**Comment by rawdigits** [comment]
the issue with hook_fd makes it sounds like the websocket isn't connected. do all normal messages come through?

**Comment by chishaku** [comment]
Yes

**Comment by rawdigits** [comment]
Try downloading the latest. just fixed a bug with unicode I introduced over the weekend.

**Comment by rawdigits** [comment]
haven't heard back, so closing this. i think it was resolved by the unicode fix.

**Comment by chishaku** [comment]
Just checked this.  Works well on my end.  Thanks for your responsiveness and a great application.

**Comment by rawdigits** [comment]
If you're ever on freenode, thank FlashCode and the people in #weechat. He writes the difficult stuff that makes a plugin like this possible. :)

**Comment by chishaku** [comment]
Will do
