### ISSUE TITLE
Part-ing a private chat gives error

### ISSUE THREAD

**Issue by hierynomus** [rawdigits/wee-slack#53]
When I `/part` a private (one-to-one) chat with a slack user, I get the following stack logged to the weechat buffer:

    12:51:52     | python: stdout/stderr: Traceback (most recent call last):
    12:51:52     | python: stdout/stderr:   File "/Users/ajvanerp/.weechat/python/autoload/wee_slack.py", line 1375, in buffer_closing_cb
    12:51:52     | python: stdout/stderr:     channels.find(data).closed()
    12:51:52     | python: stdout/stderr:   File "/Users/ajvanerp/.weechat/python/autoload/wee_slack.py", line 494, in closed
    12:51:52     | python: stdout/stderr:     message_cache.pop(self.identifier)
    12:51:52     | python: stdout/stderr: KeyError: u'D02GMQ9QT'
    12:51:52 =!= | python: error in function "buffer_closing_cb"
    12:51:53 =!= | python: wrong arguments for function "buffer_set" (script: slack_extension)
    12:51:53     | python: stdout/stderr: TypeError: must be string, not None
    12:51:53 =!= | python: error in function "slack_websocket_cb"

**Comment by rawdigits** [comment]
This shouldn't happen anymore. Private chats were recently enhanced.
