### ISSUE TITLE
feature: /topic handling

### ISSUE THREAD

**Issue by barn** [rawdigits/wee-slack#58]
Ability to /topic edit or /topic set.

Lest the:

```
irc: command "topic" must be executed on irc buffer (server or channel)
```

a hook and a callback on /topic, not sure how it will handle the cycling with tab the current command does. Good luck (:

**Comment by rawdigits** [comment]
adding code for this in the next release. easy peasy

**Comment by rawdigits** [comment]
added in #58 : https://github.com/rawdigits/wee-slack/tree/58_change_topics

lmk if you see any issues..
