### ISSUE TITLE
`/me` commands printed like IRC CTCP ACTIONs

### ISSUE THREAD

**Issue by kyrias** [rawdigits/wee-slack#61]

**Comment by rawdigits** [comment]
can you elaborate on what this means?

**Comment by kyrias** [comment]
It means that I would like it if `/me` messages in slack would be printed like CTCP ACTION commands in the IRC weechat plugin.

**Comment by tfheen** [comment]
They're sent as `_goes to do the dishes_ `, though. We could consider special-casing a message encapsulated in _ as an action, not sure if there are downsides to doing it that way.
