### ISSUE TITLE
buffers in parenthesis

### ISSUE THREAD

**Issue by kyrias** [rawdigits/wee-slack#62]
All of the slack buffers are currently printed in parenthesis for me, which is how non-connected/joined IRC buffers are printed, so it's rather distracting. I can’t find anything in the wee-slack script about it though. Any ideas?

**Comment by rawdigits** [comment]
are you using a plugin to show buffers? these are "python." buffers, so may appear differently.

**Comment by kyrias** [comment]
Oh right, it's buffers.pl. Didn't think about that. Wonder how it checks..

**Comment by rawdigits** [comment]
seems to be the setting `mark_inactive`. when i turn i do `/set buffers.look.mark_inactive off` it goes away.

**Comment by rawdigits** [comment]
i'll take a pull request to change this behavior, but not really interested in fixing it myself..
