### ISSUE TITLE
When editing the buffer with s/ style subs, I don't see my edits

### ISSUE THREAD

**Issue by seitzbg** [rawdigits/wee-slack#68]
When editing the buffer with s/ style subs, I don't see my edits.

Other users see them fine.

**Comment by tfheen** [comment]
Can you try this with the latest version? It works fine for me.

If it's still broken, I think we'll need to add some more debugging to figure out what's going on.

**Comment by rawdigits** [comment]
we haven't been able to reproduce. i suggest verifying you have a trailing / on the line. (as in "s/old/new/" not "s/old/new"
