### ISSUE TITLE
When typing a message to someone including an isolated @ fails 

### ISSUE THREAD

**Issue by seitzbg** [rawdigits/wee-slack#71]
https://www.bsd-unix.net/seitz/screenshots/2015-05-18_14-07-25.png

**Comment by rawdigits** [comment]
fixed here:
https://github.com/rawdigits/wee-slack/commit/32b784d7ef362b7866e174a578fc27010c06bddb#diff-67e177ac444a14d6bcd7be6306ab4a20R473
