### ISSUE TITLE
Please hide inactive users in the user list

### ISSUE THREAD

**Issue by seitzbg** [rawdigits/wee-slack#77]
Please hide inactive users in the user list.

16:31:05 rawdigits | i could just remove inactive users from nicklists - just haven't bothered. make an issue!

**Comment by scharfie** [comment]
If this is implemented, perhaps it can be done as a configuration option?  I personally prefer it the way it is, seeing all the users with status indicator.

**Comment by tfheen** [comment]
Active users are now grouped at the top and inactive in their own nick group. Is this ok for your? (Aka, ok to close this?)

**Comment by tfheen** [comment]
I think the current solution is sufficient, and since I've not seen anybody disagree, so closing.

**Comment by wsura-unifyone** [comment]
I agree, that hiding currently inactive users would be useful.
