### ISSUE TITLE
Nick Coloring is overly optimistic

### ISSUE THREAD

**Issue by brimstone** [rawdigits/wee-slack#79]
Examples:
- There's a user 'll' so all instances of "you'll" and "we'll" are colored as such.
- There's users, steve, steven, and steve.b, but all mentions to those people only get "steve" colored.

**Comment by rawdigits** [comment]
ah this is definitely a problem. will look at the solutions and figure out the right way to fix it up.

**Comment by rawdigits** [comment]
Looks like this was covered in #69, closing now! thanks!
