### ISSUE TITLE
Missing prompt in wee-slack buffers

### ISSUE THREAD

**Issue by pbrisbin** [rawdigits/wee-slack#80]
I use the following setting for `weechat.bar.input.items`

```
"[input_prompt]+(away),[input_search],[input_paste],input_text"
```

In a normal buffer I see

```
[brisbin(Zi)]
```

In wee-slack buffers it's completely empty.

**Comment by rawdigits** [comment]
looks fine to me! thanks for the patch.

**Comment by spectralsun** [comment]
I'm still not seeing my name in buffers?

**Comment by tfheen** [comment]
@spectralsun : I just re-added some code that got lost in a reorg. Testing would be good. :-)

**Comment by spectralsun** [comment]
@tfheen Thank you! I thought I was being gaslighted by this closed issue, haha.
