### ISSUE TITLE
Feature request: disable *some* nick coloring

### ISSUE THREAD

**Issue by pbrisbin** [rawdigits/wee-slack#81]
I like the coloring of the actual nick portion of messages, i.e. like all other weechat buffers (at least, I think this is a plugin-less default behavior of weechat).

But *not* the coloring of the nick anywhere else:

- Don't colorize the query buffers themselves. When a nick happens to be green (my default "you've been highlighted" color), I think the buffer constantly has activity. No matter how much I try to retrain my brain, this is still super frustrating.
- Don't colorize it in messages. I feel less strongly about this, but given #79, I thought it made sense to include in this feature request

It seems I can only disable *all* colorization, so my feature request is finer-grained config on these behaviors.

**Comment by pbrisbin** [comment]
Looks like #69 does this.

**Comment by rawdigits** [comment]
This one is covered by https://github.com/rawdigits/wee-slack/pull/110. Hopefully this has resolved the issue for you.
