### ISSUE TITLE
"Disconnected from slack, trying to reconnect..."

### ISSUE THREAD

**Issue by cwalkatron** [rawdigits/wee-slack#84]
I'm trying to get this set up, and I'm sure I'm just doing something foolish. I get this over and over in the weechat window. I've gotten an API token and `/set` it in the config.

```
14:15:55 SYSTEM | Disconnected from slack, trying to reconnect..                                                                          
14:15:58 SYSTEM | Disconnected from slack, trying to reconnect..                                                                          
14:16:01 SYSTEM | Disconnected from slack, trying to reconnect..                                                                          14:16:04 SYSTEM | Disconnected from slack, trying to reconnect..                                                                          
14:16:07 SYSTEM | Disconnected from slack, trying to reconnect..                                                                          
14:16:10 SYSTEM | Disconnected from slack, trying to reconnect..
```

Debug output is only: `14:15:54 | DEBUG: connected to pixar.slack.com`

Thanks for any help.

**Comment by rawdigits** [comment]
give it another shot with the new version. there is also a chance that curl isn't installed on the machine. make sure you can run `curl www.google.com` successfully

**Comment by cwalkatron** [comment]
The new version still had this problem. I did some sleuthing and traced this down to a old version of `websocket-client` (0.14.0). I updated to the latest (0.32.0) and it all works. Sorry for the trouble!

**Comment by rawdigits** [comment]
Oh! this is excellent info. I should mention a version of websocket-client in the README!

**Comment by cwalkatron** [comment]
The `except` here: https://github.com/rawdigits/wee-slack/blob/master/wee_slack.py#L247 was masking the error. Weechat users on our team will love this! Thanks again.

**Comment by rawdigits** [comment]
much appreciated! printing the exception now: https://github.com/rawdigits/wee-slack/commit/48988c464e54bad25323487bc875f0f3d88b9b24

**Comment by Yavor-Ivanov** [comment]
The new 0.34.0 version of `websocket-client` will not work either. I get the same error message, but no debug output with it. Downgrading to 0.32.0 works.

**Comment by bchretien** [comment]
@Yavor-Ivanov you probably have the issue described here: https://github.com/rawdigits/wee-slack/issues/122
