### ISSUE TITLE
Beep on channel message

### ISSUE THREAD

**Issue by dax0** [rawdigits/wee-slack#87]
Is there a way to turn on notifications so it beeps on certain channel messages? Thanks

**Comment by rawdigits** [comment]
not sure? does weechat have this feature ?

**Comment by dax0** [comment]
There are plugins that enable this but I figured you could just add a setting for this and create a beep from Python

**Comment by dax0** [comment]
Not sure if you can see this info but ideally it would beep on channels where notifications are enabled for every message in Slack

**Comment by ainola** [comment]
My usage of slack is with ~6 or 7 people, so usually every message does need to be read. #101 
and an audio notification for channel+private messages would be lovely.... it just might be quite an undertaking.

weechat has beep.pl: https://weechat.org/scripts/source/beep.pl.html/

**Comment by rawdigits** [comment]
ah beep.pl seems like a pretty good solution and a cursory look at the code says that it'll work with wee-slack! let me know if you have issues.
