### ISSUE TITLE
Opening #general causes weechat to freeze for 30-45 seconds

### ISSUE THREAD

**Issue by o2dazone** [rawdigits/wee-slack#89]
If I quit weechat and open it back up, the #general channel will freeze the weechat process for about half a minute. After that, everything is fine. Leaving #general via /close and rejoining will cause the same freeze up. The slack-debug channel does not show any clear problems

 ```shell
DEBUG: connected to <omitted>.slack.com
DEBUG: Function not implemented: hello
{u'type': u'hello', 'myserver': '<omitted>.slack.com'}
DEBUG: Sent {"type": "ping", "id": 1}...
DEBUG: REPLY {'type': 'ping', 'id': 1}
DEBUG: Unexpected error: <class 'socket.error'>
Sent: {'type': 'ping', 'id': 2}
DEBUG: Unexpected error: <class 'socket.error'>
Sent: {'type': 'ping', 'id': 3}
DEBUG: connected to <omitted>.slack.com
DEBUG: Function not implemented: hello
{u'type': u'hello', 'myserver': '<omitted>.slack.com'}
DEBUG: Sent {"type": "ping", "id": 1}...
DEBUG: REPLY {'type': 'ping', 'id': 1}
DEBUG: Sent {"type": "ping", "id": 2}...
DEBUG: REPLY {'type': 'ping', 'id': 2}
DEBUG: Sent {"type": "ping", "id": 3}...
```

**Comment by o2dazone** [comment]
Looks to be an issue with processing joins/leaves. In #general, with a big company, this is a huge amount of processing.

```
        # send these messages elsewhere
        known_subtypes = ['channel_join', 'channel_leave', 'channel_topic']
        if "subtype" in message_json and message_json["subtype"] in known_subtypes:
            proc[message_json["subtype"]](message_json)
```

removing the proc[...] line makes the client start up immediately. Something seems to halt the client when pushing to the proc array.

**Comment by Jayphen** [comment]
I had the same problem, except the process would freeze and use 100% CPU until I killed it (I waited 10 minutes). I'm in a channel with 4000 active users though…

**Comment by tfheen** [comment]
@o2dazone, that isn't actually pushing to an array, it looks up the subtype in the proc map and calls the function it points to.

If it takes a very long time, I suspect we're doing lookups in an array instead of a set/dictionary, leading to O(n^2) runtimes.

**Comment by tfheen** [comment]
@Jayphen, we've included a bunch of performance speedups now. Can you see if git head works better for you?

**Comment by o2dazone** [comment]
Problem still persists after doing a pull today.
![weeslack_cpu](https://cloud.githubusercontent.com/assets/1907517/9584297/456ae0fa-4fc5-11e5-8e47-db473b43b558.png)

**Comment by Jayphen** [comment]
I'm also still having this issue, using Weechat 1.3.
