### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by ersuniljoshi** [rawdigits/wee-slack#98]
This is happening while loading the plugin
i.e. /python reload

python: stdout/stderr: __weechat_plugin__:80: UnicodeWarning: Unicode equal comparison failed to convert both arguments to
Unicode
- interpreting them as being unequal
python: stdout/stderr: __weechat_plugin__:725: UnicodeWarning: Unicode equal comparison failed to convert both arguments to
Unicode - interpreting them as being unequal
python: stdout/stderr: __weechat_plugin__:563: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to
Unicode - interpreting them as being unequal

**Comment by megalithic** [comment]
I'm presently getting this same error when doing string substitution from in a slack channel: https://gist.github.com/megalithic/c2b1cb38c6deeb482621

also, i have python and python3 installed (both via homebrew); i installed weechat via homebrew like so:
`brew install weechat --with-ruby --with-python --with-perl`

**Comment by terlar** [comment]
Also getting these warnings. Running Arch Linux and Weechat  1.3.

**Comment by adamgruber** [comment]
Yup, me too. OS X 10.10.5

**Comment by fuzzy76** [comment]
Is this related?

```
10:07 python: stdout/stderr: Traceback (most recent call last):
10:07 python: stdout/stderr:   File "/home/fuzzy76/.weechat/python/autoload/wee_slack.py", line 1753, in url_processor_cb
10:07 python: stdout/stderr:     process_message(message)
10:07 python: stdout/stderr:   File "/home/fuzzy76/.weechat/python/autoload/wee_slack.py", line 1439, in process_message
10:07 python: stdout/stderr:     channel.buffer_prnt('unknown', message_json['text'])
10:07 python: stdout/stderr:   File "/home/fuzzy76/.weechat/python/autoload/wee_slack.py", line 587, in buffer_prnt
10:07 python: stdout/stderr:     message = message.decode('UTF-8', 'replace')
10:07 python: stdout/stderr:   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
10:07 python: stdout/stderr:     return codecs.utf_8_decode(input, errors, True)
10:07 python: stdout/stderr: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 146: ordinal not in range(128)
10:07 =!= python: error in function "url_processor_cb"
```

**Comment by rawdigits** [comment]
good old unicode. :) i haven't been able to reproduce this yet, but it seems like unicode in names may be the problem. @megalithic do you mind sharing your slack name in the comment here?

**Comment by megalithic** [comment]
@rawdigits certainly; it is literally: `megalithic`

my problem has always been that i'm unable to take advantage of in-place string replacement: `s/foo/foobar`.

now, that could certainly derive from the fact that folks use unicode names in the same slack channel that i'm executing that.

**Comment by rawdigits** [comment]
Just spent some time trying to repro this and I'm pretty sure it no longer exists. I'll leave it open for now, and close it the next time we work on issues if I don't hear any news.

**Comment by rawdigits** [comment]
actually going to close this as we haven't seen these for a while. we think they were fixed but not sure which commit...

**Comment by the-solipsist** [comment]
I'm getting the same error (latest version: 0.99.9, downloaded today), when I type /python reload:

python: stdout/stderr: __weechat_plugin__:93: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

python: stdout/stderr: __weechat_plugin__:845: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
