### ISSUE TITLE
join messages are getting displayed in weechat, even its turned off globally.

### ISSUE THREAD

**Issue by ersuniljoshi** [rawdigits/wee-slack#99]
3.19.0-25-generic #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Weechat version -  WeeChat 1.3-dev [compiled on Jul 27 2015 18:42:33]

**Comment by tfheen** [comment]
The smart irc filter works for me in recent versions. Is that what you're using, or something else? Can you check if this is still a problem?

**Comment by rawdigits** [comment]
I definitely have join messages filtered the normal way and don't see them. This can likely be closed @tfheen

**Comment by tfheen** [comment]
Ok, closing this since it works for multiple people. Please reopen if this is still a problem.
